# Generated by Django 2.1.1 on 2018-11-06 19:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text="The game's title", max_length=100)),
                ('online', models.BooleanField(default=True)),
                ('description', models.CharField(default='', help_text="The game's description", max_length=100)),
                ('link', models.CharField(default='', help_text="A link to this game's website", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', help_text='The text content of the message', max_length=100)),
                ('datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The name of the platform (e.g. PlayStation 4)', max_length=100)),
                ('games', models.ManyToManyField(blank=True, to='PlayWithMe.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text="The Profile's username", max_length=20)),
                ('password', models.CharField(help_text="The profile's password", max_length=20)),
                ('games', models.ManyToManyField(blank=True, to='PlayWithMe.Game')),
                ('platforms', models.ManyToManyField(blank=True, to='PlayWithMe.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(help_text='ID to uniquely identify a session', max_length=60, primary_key=True, serialize=False)),
                ('location', models.CharField(default='', help_text="The session's location", max_length=100)),
                ('online', models.BooleanField(default=True)),
                ('games', models.ManyToManyField(blank=True, to='PlayWithMe.Game')),
                ('messages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PlayWithMe.Message')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='PlayWithMe.Profile')),
                ('platforms', models.ManyToManyField(blank=True, to='PlayWithMe.Platform')),
                ('profiles', models.ManyToManyField(to='PlayWithMe.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='PlayWithMe.Session'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sessions_owned',
            field=models.ManyToManyField(blank=True, related_name='sessions_owned', to='PlayWithMe.Session'),
        ),
        migrations.AddField(
            model_name='message',
            name='context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PlayWithMe.Session'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PlayWithMe.Profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='PlayWithMe.Platform'),
        ),
    ]
