# Generated by Django 2.1.1 on 2018-11-05 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayWithMe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text="The Profile's username", max_length=20)),
                ('password', models.CharField(help_text="The profile's password", max_length=20)),
                ('games', models.ManyToManyField(blank=True, to='PlayWithMe.Game')),
                ('platforms', models.ManyToManyField(blank=True, to='PlayWithMe.Platform')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='games',
        ),
        migrations.RemoveField(
            model_name='user',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sessions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sessions_owned',
        ),
        migrations.RemoveField(
            model_name='session',
            name='users',
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PlayWithMe.Profile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='PlayWithMe.Profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='PlayWithMe.Session'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sessions_owned',
            field=models.ManyToManyField(blank=True, related_name='sessions_owned', to='PlayWithMe.Session'),
        ),
        migrations.AddField(
            model_name='session',
            name='Profiles',
            field=models.ManyToManyField(to='PlayWithMe.Profile'),
        ),
    ]
