# Generated by Django 2.1.1 on 2018-11-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayWithMe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='messages',
        ),
        migrations.AddField(
            model_name='session',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, to='PlayWithMe.Message'),
        ),
    ]
