# Generated by Django 2.1.1 on 2018-11-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayWithMe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(help_text='Name of the session', max_length=100, null=True),
        ),
    ]
