# Generated by Django 2.1.1 on 2018-10-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayWithMe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', help_text='Enter your password', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=20),
        ),
    ]
