# Generated by Django 2.1.1 on 2018-11-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayWithMe', '0002_auto_20181106_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='PlayWithMe.Profile'),
        ),
    ]
