# Generated by Django 2.1.1 on 2018-11-06 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayWithMe', '0002_auto_20181106_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='messages',
        ),
        migrations.AddField(
            model_name='session',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PlayWithMe.Message'),
        ),
    ]
