# Generated by Django 2.1.1 on 2018-10-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayWithMe', '0002_auto_20181030_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Enter your password', max_length=20),
        ),
    ]
