# Generated by Django 2.1.1 on 2018-11-02 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayWithMe', '0004_auto_20181030_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sessions_owned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_owned', to='PlayWithMe.Session'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sessions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='PlayWithMe.Session'),
        ),
    ]
