# Generated by Django 2.1.1 on 2018-11-02 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayWithMe', '0006_auto_20181102_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.CharField(default='', help_text="The session's location", max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='session',
            name='platforms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PlayWithMe.Platform'),
        ),
        migrations.AddField(
            model_name='session',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PlayWithMe.Message'),
        ),
    ]
