# Generated by Django 2.1.1 on 2018-11-02 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayWithMe', '0007_auto_20181102_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(default='', help_text="The game's description", max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.CharField(default='', help_text="A link to this game's website", max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PlayWithMe.Platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='', help_text="The game's title", max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text="The user's password", max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text="The user's username", max_length=20),
        ),
    ]
