# Generated by Django 2.1.1 on 2018-11-02 22:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayWithMe', '0008_auto_20181102_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='context',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PlayWithMe.Session'),
        ),
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PlayWithMe.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.CharField(default='', help_text='The text content of the message', max_length=100),
        ),
        migrations.AddField(
            model_name='platform',
            name='games',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PlayWithMe.Game'),
        ),
        migrations.AddField(
            model_name='platform',
            name='name',
            field=models.CharField(default='', help_text='The name of the platform (e.g. PlayStation 4)', max_length=100),
        ),
    ]
