# Generated by Django 2.1.1 on 2018-11-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayWithMe', '0009_auto_20181102_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sessions_owned',
        ),
    ]
