# Generated by Django 2.1.1 on 2018-11-02 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayWithMe', '0010_remove_user_sessions_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sessions_owned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_owned', to='PlayWithMe.Session'),
        ),
    ]
