# Generated by Django 2.1.1 on 2018-11-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayWithMe', '0011_user_sessions_owned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='sender',
        ),
    ]
